"use client";

import { siteConfig } from "../config/site";
import { Icons } from "./Icons";
import Link from "next/link";

export function SiteFooter() {
  return (
    <footer className="container bg-white text-slate-600">
      <div className="flex flex-col items-center justify-between gap-4 border-t border-t-slate-200 py-10 md:h-24 md:flex-row md:py-0">
        <div className="flex flex-col items-center gap-4 px-8 md:flex-row md:gap-2 md:px-0">
          <Icons.logo />
          <p className="text-center text-sm leading-loose md:text-left">
            Built by{" "}
            <Link
              href={siteConfig.links.linkedIn}
              target="_blank"
              className="font-medium underline underline-offset-4"
            >
              Adam Ksiazek
            </Link>
            . Illustrations generated by{" "}
            <Link
              href="https://midjourney.com/"
              target="_blank"
              className="font-medium underline underline-offset-4"
            >
              Midjourney
            </Link>
            .
          </p>
        </div>
      </div>
    </footer>
  );
}
